sudo: required

language: ruby

services:
    - docker

before_install:
    - docker pull carlad/sinatra

script:
    - docker images
    - docker ps

notifications:
 slack:
   rooms:
     - dohxyah:ECnJMqa9YGLiB0cYug0GPXQF#general
#     - dohxyah:ECnJMqa9YGLiB0cYug0GPXQF#random

